---
ami: 'ami-039d523dc6a4d52ab'
type: 't2.xlarge'
block_devices:
  - name: '/dev/sda1'
    size: 30
  - name: 'xvdf'
    size: 1400
inbounds:
  - ip: '222.126.242.202/32'
    port:
      - 21-22
      - 3389
      - 443
      - 80
    description: 'from office'